name: static_code_analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        python-version: 3.8
      - name: Conda install
        shell: bash -l {0}
        run: conda install -c conda-forge poetry
      - run: poetry install
      - run: ruff check guided_tamp_benchmark
      - run: black --check --diff --verbose guided_tamp_benchmark
      - run: pytest
